### ISSUE TITLE
Add notInclude input

### ISSUE THREAD

**Issue by eniskastrati** [Jodebu/upload-to-drive#19]
maybe create something like this
``` yaml
name: Store public in Drive
on:
  push: { branches: [master] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload public to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload public folder to Google Drive
        uses: Jodebu/upload-to-drive@master
        id: driveUpload
        with:
          target: public
          notInclude: docs
          credentials: secrets.<YOUR_DRIVE_CREDENTIALS>
          folder: <YOUR_DRIVE_FOLDER_ID>
```

So I would really appreciate to have a paramter which will not include a specifc folder of file
